<?php
declare(strict_types=1);
function e(string $s): string { return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function fail404(): never { http_response_code(404); echo '<!doctype html><title>Job not found | JobsOther</title><h1>Job not found</h1><p><a href="/jobs.html">Search current jobs</a></p>'; exit; }
$id=trim((string)($_GET['id']??'')); if($id==='') fail404();
$appId=getenv('ADZUNA_APP_ID')?:''; $appKey=getenv('ADZUNA_APP_KEY')?:'';
$configPath=dirname(__DIR__).'/jobsother-config.php';
if((!$appId||!$appKey)&&is_file($configPath)){ $c=require $configPath; if(is_array($c)){ $appId=$appId?:((string)($c['ADZUNA_APP_ID']??'')); $appKey=$appKey?:((string)($c['ADZUNA_APP_KEY']??'')); }}
if(!$appId||!$appKey){ http_response_code(503); exit('Job service temporarily unavailable.'); }
$url='https://api.adzuna.com/v1/api/jobs/ca/details/'.rawurlencode($id).'?'.http_build_query(['app_id'=>$appId,'app_key'=>$appKey]);
$body=false;$status=0;
if(function_exists('curl_init')){$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>18,CURLOPT_HTTPHEADER=>['Accept: application/json'],CURLOPT_USERAGENT=>'JobsOther/1.0']);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);}
else{$ctx=stream_context_create(['http'=>['timeout'=>18,'header'=>"Accept: application/json\r\nUser-Agent: JobsOther/1.0\r\n",'ignore_errors'=>true]]);$body=@file_get_contents($url,false,$ctx);if(isset($http_response_header[0])&&preg_match('/\s(\d{3})\s/',$http_response_header[0],$m))$status=(int)$m[1];}
if($body===false||$status<200||$status>=300) fail404();
$j=json_decode((string)$body,true); if(!is_array($j)||empty($j['title'])) fail404();
$title=trim((string)$j['title']);$company=trim((string)($j['company']['display_name']??''));$location=trim((string)($j['location']['display_name']??''));$desc=trim(strip_tags((string)($j['description']??'')));$created=(string)($j['created']??'');$apply=(string)($j['redirect_url']??'');$type=(string)($j['contract_time']??'');$contract=(string)($j['contract_type']??'');$salaryMin=$j['salary_min']??null;$salaryMax=$j['salary_max']??null;$lat=$j['latitude']??null;$lng=$j['longitude']??null;
$slug=preg_replace('/[^a-z0-9]+/','-',strtolower($title.' '.$company));$slug=trim((string)$slug,'-');$canonical='https://jobsother.com/job/'.rawurlencode($id).'/'.rawurlencode(substr($slug,0,90)).'/';
$metaDesc=mb_substr($title.($company?' at '.$company:'').($location?' in '.$location:'').'. '.$desc,0,155);
$schema=['@context'=>'https://schema.org','@type'=>'JobPosting','title'=>$title,'description'=>$desc,'identifier'=>['@type'=>'PropertyValue','name'=>$company?:'JobsOther source','value'=>$id],'datePosted'=>$created,'hiringOrganization'=>['@type'=>'Organization','name'=>$company?:'Employer'],'directApply'=>false];
if($type||$contract){$map=['full_time'=>'FULL_TIME','part_time'=>'PART_TIME','permanent'=>'FULL_TIME','contract'=>'CONTRACTOR'];$raw=$type?:$contract;$schema['employmentType']=$map[$raw]??strtoupper($raw);}
$address=['@type'=>'PostalAddress','addressCountry'=>'CA']; if($location)$address['addressLocality']=$location;$schema['jobLocation']=['@type'=>'Place','address'=>$address];if($lat!==null&&$lng!==null)$schema['jobLocation']['geo']=['@type'=>'GeoCoordinates','latitude'=>$lat,'longitude'=>$lng];
if($salaryMin!==null||$salaryMax!==null){$v=['@type'=>'QuantitativeValue','unitText'=>'YEAR'];if($salaryMin!==null)$v['minValue']=$salaryMin;if($salaryMax!==null)$v['maxValue']=$salaryMax;$schema['baseSalary']=['@type'=>'MonetaryAmount','currency'=>'CAD','value'=>$v];}
?><!doctype html><html lang="en"><head>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C3TNC6YFYV"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-C3TNC6YFYV');</script>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title.($company?' at '.$company:'').' | JobsOther')?></title><meta name="description" content="<?=e($metaDesc)?>"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="<?=e($canonical)?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP)?></script>
<style>:root{--o:#f47a1f;--ink:#202733;--muted:#667085;--line:#e5e7eb}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,"Segoe UI",Arial,sans-serif;background:#f7f8fa;color:var(--ink)}a{text-decoration:none;color:inherit}.wrap{width:min(940px,calc(100% - 32px));margin:auto}header{background:#fff;border-bottom:1px solid var(--line)}.nav{height:70px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:26px;font-weight:800}.brand b{color:var(--o)}.crumb{margin-top:24px;color:#667085;font-size:13px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:32px;margin:14px 0 35px}h1{font-size:34px;line-height:1.2;margin:0 0 9px}.company{font-size:18px;font-weight:700;color:#475467}.meta{display:flex;gap:8px;flex-wrap:wrap;margin:17px 0 24px}.badge{background:#f3f4f6;padding:7px 10px;border-radius:999px;color:#667085;font-size:13px}.desc{white-space:pre-line;line-height:1.75;color:#4b5563}.btn{display:inline-block;background:var(--o);color:#fff;padding:12px 18px;border-radius:9px;font-weight:800;margin-top:24px}.note{font-size:12px;color:#98a2b3;margin-top:12px}@media(max-width:600px){.card{padding:22px}h1{font-size:28px}}</style></head><body><header><div class="wrap nav"><a class="brand" href="/">Jobs<b>Other</b></a><a href="/jobs.html">Find Jobs</a></div></header><main class="wrap"><div class="crumb"><a href="/">Home</a> › <a href="/jobs.html">Jobs</a> › <?=e($title)?></div><article class="card"><h1><?=e($title)?></h1><?php if($company):?><div class="company"><?=e($company)?></div><?php endif?><div class="meta"><?php if($location):?><span class="badge">📍 <?=e($location)?></span><?php endif?><?php if($type):?><span class="badge">🕒 <?=e(str_replace('_',' ',$type))?></span><?php endif?><?php if($created):?><span class="badge">Posted <?=e(substr($created,0,10))?></span><?php endif?></div><h2>Job description</h2><div class="desc"><?=nl2br(e($desc))?></div><?php if($apply):?><a class="btn" href="<?=e($apply)?>" target="_blank" rel="noopener sponsored">Apply at original source ↗</a><div class="note">You will continue your application on the original job provider or employer website.</div><?php endif?></article></main></body></html>