<?php
declare(strict_types=1);
$keywordSlug=trim((string)($_GET['keyword']??''));
$locationSlug=trim((string)($_GET['location']??''));
$knownLocations=['vancouver-bc'=>'Vancouver, BC','toronto-on'=>'Toronto, ON','calgary-ab'=>'Calgary, AB','edmonton-ab'=>'Edmonton, AB','ottawa-on'=>'Ottawa, ON','surrey-bc'=>'Surrey, BC','burnaby-bc'=>'Burnaby, BC','richmond-bc'=>'Richmond, BC','winnipeg-mb'=>'Winnipeg, MB','victoria-bc'=>'Victoria, BC','mississauga-on'=>'Mississauga, ON','brampton-on'=>'Brampton, ON'];
$knownKeywords=['warehouse'=>'warehouse','delivery-driver'=>'delivery driver','customer-service'=>'customer service','part-time'=>'part time','work-from-home'=>'work from home','remote'=>'remote','administrative-assistant'=>'administrative assistant','cashier'=>'cashier','cleaner'=>'cleaner','construction'=>'construction','healthcare'=>'healthcare','restaurant'=>'restaurant','sales-associate'=>'sales associate','general-labour'=>'general labour','truck-driver'=>'truck driver','software-developer'=>'software developer'];
if($locationSlug==='' && isset($knownLocations[$keywordSlug])){$locationSlug=$keywordSlug;$keywordSlug='';}
$keyword=$knownKeywords[$keywordSlug]??str_replace('-',' ',$keywordSlug);
$location=$knownLocations[$locationSlug]??ucwords(str_replace('-',' ',$locationSlug));
$h1=($keyword?ucwords($keyword).' Jobs':'Jobs').($location?' in '.$location:' in Canada');
$title=$h1.' | JobsOther';
$desc='Browse the latest '.($keyword?:'job').' opportunities'.($location?' in '.$location:' across Canada').'. Search full-time, part-time, entry-level, remote and local jobs and apply online.';
$canonical='https://jobsother.com/jobs/'.($keywordSlug?rawurlencode($keywordSlug).'/':'').($locationSlug?rawurlencode($locationSlug).'/':'');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?></title><meta name="description" content="<?=htmlspecialchars($desc)?>"><meta name="robots" content="index,follow"><link rel="canonical" href="<?=htmlspecialchars($canonical)?>"><script type="application/ld+json"><?=json_encode(["@context"=>"https://schema.org","@type"=>"CollectionPage","name"=>$h1,"description"=>$desc,"url"=>$canonical],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><style>body{font-family:Arial,sans-serif;margin:0;background:#f7f8fa;color:#202733}.wrap{max-width:980px;margin:auto;padding:24px}.card{background:#fff;border:1px solid #ddd;border-radius:12px;padding:20px;margin-bottom:12px}a{color:#d8610d;text-decoration:none}.links{line-height:2}.intro{color:#596273;line-height:1.65}</style></head><body><div class="wrap"><p><a href="/">JobsOther</a> › <a href="/popular-jobs.html">Popular Jobs</a></p><h1><?=htmlspecialchars($h1)?></h1><p class="intro"><?=htmlspecialchars($desc)?></p><div id="jobs"><p>Loading jobs…</p></div><div class="card"><h2>Popular job searches</h2><p class="links"><a href="/jobs/warehouse/">Warehouse Jobs</a> · <a href="/jobs/delivery-driver/">Delivery Driver Jobs</a> · <a href="/jobs/customer-service/">Customer Service Jobs</a> · <a href="/jobs/part-time/">Part-Time Jobs</a> · <a href="/jobs/work-from-home/">Work From Home Jobs</a> · <a href="/jobs/remote/">Remote Jobs</a> · <a href="/jobs/administrative-assistant/">Administrative Assistant Jobs</a> · <a href="/jobs/cashier/">Cashier Jobs</a> · <a href="/jobs/cleaner/">Cleaning Jobs</a> · <a href="/jobs/construction/">Construction Jobs</a> · <a href="/jobs/healthcare/">Healthcare Jobs</a> · <a href="/jobs/restaurant/">Restaurant Jobs</a> · <a href="/jobs/sales-associate/">Sales Associate Jobs</a> · <a href="/jobs/general-labour/">General Labour Jobs</a> · <a href="/jobs/truck-driver/">Truck Driver Jobs</a> · <a href="/jobs/software-developer/">Software Developer Jobs</a></p><h2>Jobs by city</h2><p class="links"><a href="/jobs/vancouver-bc/">Vancouver, BC</a> · <a href="/jobs/toronto-on/">Toronto, ON</a> · <a href="/jobs/calgary-ab/">Calgary, AB</a> · <a href="/jobs/edmonton-ab/">Edmonton, AB</a> · <a href="/jobs/ottawa-on/">Ottawa, ON</a> · <a href="/jobs/surrey-bc/">Surrey, BC</a> · <a href="/jobs/burnaby-bc/">Burnaby, BC</a> · <a href="/jobs/richmond-bc/">Richmond, BC</a> · <a href="/jobs/winnipeg-mb/">Winnipeg, MB</a> · <a href="/jobs/victoria-bc/">Victoria, BC</a> · <a href="/jobs/mississauga-on/">Mississauga, ON</a> · <a href="/jobs/brampton-on/">Brampton, ON</a></p></div></div><script>
const q=<?=json_encode($keyword)?>,loc=<?=json_encode($location)?>;fetch('/api/jobs.php?q='+encodeURIComponent(q)+'&location='+encodeURIComponent(loc)+'&results_per_page=20').then(r=>r.json()).then(d=>{document.getElementById('jobs').innerHTML=(d.results||[]).map(j=>'<div class="card"><h2><a href="/job.html?id='+encodeURIComponent(j.id)+'&q='+encodeURIComponent(q)+'&location='+encodeURIComponent(loc)+'">'+String(j.title).replace(/[<>]/g,'')+'</a></h2><strong>'+String(j.company||'').replace(/[<>]/g,'')+'</strong><p>'+String(j.location||'').replace(/[<>]/g,'')+'</p><p>'+String(j.description||'').replace(/[<>]/g,'').slice(0,220)+'…</p></div>').join('')||'<p>No jobs found right now. Try another nearby city or job type.</p>'});
</script></body></html>