CREATE TABLE jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 external_id VARCHAR(191) NOT NULL,
 source VARCHAR(60) NOT NULL,
 title VARCHAR(255) NOT NULL,
 company VARCHAR(255) DEFAULT '',
 company_logo TEXT,
 location VARCHAR(255) DEFAULT '',
 city VARCHAR(120) DEFAULT '',
 province VARCHAR(120) DEFAULT '',
 country CHAR(2) DEFAULT 'CA',
 postal_code VARCHAR(20) DEFAULT '',
 latitude DECIMAL(10,7) NULL,
 longitude DECIMAL(10,7) NULL,
 salary_min DECIMAL(12,2) NULL,
 salary_max DECIMAL(12,2) NULL,
 salary_currency CHAR(3) DEFAULT 'CAD',
 salary_period VARCHAR(40) NULL,
 employment_type VARCHAR(80) DEFAULT '',
 category VARCHAR(120) DEFAULT '',
 description MEDIUMTEXT,
 short_description TEXT,
 apply_url TEXT,
 source_url TEXT,
 posted_at DATETIME NULL,
 expires_at DATETIME NULL,
 is_featured TINYINT(1) DEFAULT 0,
 is_sponsored TINYINT(1) DEFAULT 0,
 is_remote TINYINT(1) DEFAULT 0,
 is_new TINYINT(1) DEFAULT 0,
 dedupe_hash CHAR(64) NOT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uniq_source_external (source, external_id),
 KEY idx_dedupe (dedupe_hash),
 KEY idx_location (city, province),
 KEY idx_posted (posted_at)
);
CREATE TABLE job_alerts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 first_name VARCHAR(80) DEFAULT '',
 email VARCHAR(255) NOT NULL,
 keyword VARCHAR(120) NOT NULL,
 location VARCHAR(120) DEFAULT '',
 radius_km INT DEFAULT 25,
 frequency ENUM('daily','weekly') DEFAULT 'daily',
 status ENUM('active','unsubscribed') DEFAULT 'active',
 unsubscribe_token CHAR(48) NOT NULL,
 last_sent_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 UNIQUE KEY uniq_token (unsubscribe_token),
 KEY idx_alert_email (email),
 KEY idx_alert_status (status)
);